FROM python:3.10.6-bullseye


#COPY requirements.txt .
#RUN pip install -r requirements.txt
#CMD python main.py

SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git sd-opt
RUN useradd -m sd
RUN chown -R sd:sd sd-opt
WORKDIR sd-opt

COPY v2-1_768-ema-pruned.ckpt models/Stable-diffusion/sd2-1.ckpt

COPY webui-user.sh webui-user.sh

#COPY main.py .

RUN chmod +x webui.sh && cd ..

USER sd

RUN source ./webui-user.sh

#RUN pip install -r requirements_versions.txt && pip install -r requirements.txt

COPY install.py .
#RUN python main.py --xformers --exit --skip-torch-cuda-test
COPY install.sh .
RUN ./install.sh

EXPOSE 7861 7860
#COPY main.py .
COPY run.sh .
CMD ./run.sh
